language: bash
dist: bionic
addons:
  apt:
    packages:
      - zstd
services:
  - docker
cache:
  directories:
  - docker
before_install:
 - mkdir -p docker
 - if [[ -e docker/texbuilder.zst  ]] ; then echo found ; zstdcat docker/texbuilder.zst | docker load ; else docker pull makisyu/texlive-2017 ; docker save makisyu/texlive-2017 | zstd -14 -T0 -o docker/texbuilder.zst; fi
script:
- docker run -v `pwd`/:/mnt/ makisyu/texlive-2017 /bin/bash -c "cd /mnt/src && make test"
- mkdir out/
- cp pdf/*.pdf out/
notifications:
  slack: ftsrg:qnSMPdAdgpSj9vVxcl2AB2qU
  on_success: change
  on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: out
  github-token: $GITHUB_TOKEN
  on:
    branch: master
